version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Running tests
          command: npm run build
      - run:
          name: Install codeclimate reporter
          command: sudo npm install -g codeclimate-test-reporter
      - run:
          name: Upload test result to codeclimate
          command: codeclimate-test-reporter < coverage/lcov.info
      - run:
          name: Upload test result to codecov
          command: bash <(curl -s https://codecov.io/bash)